remote_theme: mmistakes/minimal-mistakes
title: Klub Biatlonu Chotěboř
minimal_mistakes_skin: "air"
plugins:
  - jekyll-include-cache
  - jekyll-feed
locale: cs

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name   : "Biatlon v Chotě"
  avatar : "/assets/images/biatlon-logo.png"
  bio    : "Chceš si biatlon [vyzkoušet na vlastní kůži](/pridej-se/)? Mrkni [v čem je jeho kouzlo](/o-biatlonu/) a [ozvi se nám](/kontakt/)."
  links:
    - label: "biatlon.chotebor@centrum.cz"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:biatlon.chotebor@centrum.cz"
    - label: "Fotky na Rajčeti"
      icon: "fas fa-fw fa-link"
      url: "https://biatlonchotebor.rajce.idnes.cz/"
    - label: "Tymuj.cz"
      icon: "fas fa-fw fa-link"
      url: "https://app.tymuj.cz/teams/19234"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

footer:
  links:
    - label: "Biatlon.cz"
      icon: "fas fa-fw fa-link"
      url: "https://www.biatlon.cz"
    - label: "Rozpis závodů"
      icon: "fas fa-fw fa-link"
      url: "https://evidence.biatlon.cz/#/udalosti"
    - label: "Online výsledky"
      icon: "fas fa-fw fa-link"
      url: "http://online.biatlon.cz"
    - label: "Plán tréninků"
      icon: "fas fa-fw fa-link"
      url: "https://docs.google.com/document/d/1bCtcN3SRhM2kunS8DVi4wrvGvTJ9cIkXPdTv8_0Nb6o/edit?usp=sharing"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"
