remote_theme: mmistakes/minimal-mistakes
title: Biatlon Chotebor
minimal_mistakes_skin: "air"
plugins:
  - jekyll-include-cache
  - jekyll-feed
locale: cs
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name   : "Biatlon Chotebor"
  avatar : "/assets/images/gallery/tym/jablonec2025.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "biatlon.chotebor@centrum.cz"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:biatlon.chotebor@centrum.cz"
    - label: "Fotky na Rajceti"
      icon: "fas fa-fw fa-link"
      url: "https://biatlonchotebor.rajce.idnes.cz/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "Biatlon.cz"
      icon: "fas fa-fw fa-link"
      url: "https://www.biatlon.cz"
    - label: "Evidence a zavody"
      icon: "fas fa-fw fa-link"
      url: "https://evidence.biatlon.cz"
    - label: "Online Biatlon"
      icon: "fas fa-fw fa-link"
      url: "http://online.biatlon.cz"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
